package com.lesssoda.miaosha.dao;

import com.lesssoda.miaosha.dataobject.ItemDO;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;


@Repository
public interface ItemDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Thu Mar 25 15:49:38 GMT+08:00 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Thu Mar 25 15:49:38 GMT+08:00 2021
     */
    int insert(ItemDO record);


    /**
     * 商品列表
     * @return
     */
    List<ItemDO> listItem();



    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Thu Mar 25 15:49:39 GMT+08:00 2021
     */
    int insertSelective(ItemDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Thu Mar 25 15:49:39 GMT+08:00 2021
     */
    ItemDO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Thu Mar 25 15:49:39 GMT+08:00 2021
     */
    int updateByPrimaryKeySelective(ItemDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item
     *
     * @mbg.generated Thu Mar 25 15:49:39 GMT+08:00 2021
     */
    int updateByPrimaryKey(ItemDO record);

    /**
     *
     * @return
     */
    int increaseSales(@Param("id")Integer id, @Param("amount")Integer amount);
}