package com.lesssoda.miaosha.dao;

import com.lesssoda.miaosha.dataobject.ItemStockDO;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;


@Repository
public interface ItemStockDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Thu Mar 25 15:49:39 GMT+08:00 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Thu Mar 25 15:49:39 GMT+08:00 2021
     */
    int insert(ItemStockDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Thu Mar 25 15:49:39 GMT+08:00 2021
     */
    int insertSelective(ItemStockDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Thu Mar 25 15:49:39 GMT+08:00 2021
     */
    ItemStockDO selectByPrimaryKey(Integer id);


    /**
     * 根据ItemId查找库存
     * @param id
     * @return
     */
    ItemStockDO selectByItemId(Integer id);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Thu Mar 25 15:49:39 GMT+08:00 2021
     */
    int updateByPrimaryKeySelective(ItemStockDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Thu Mar 25 15:49:39 GMT+08:00 2021
     */
    int updateByPrimaryKey(ItemStockDO record);

    /**
     * 减库存
     * @param itemId
     * @param amount
     * @return
     */
    int decreaseStock(@Param("itemId")Integer itemId, @Param("amount")Integer amount);
}